/**
 * @author PT Docheck Bagi Indonesia
 * @copyright © All rights reserved. DoCheck 2022
 */

const images = {
    doCheckLogoIcon: require('./images/logo.png'),
    recommendationGoals: require('./images/recommendationGoalsPlaceholder.jpg'),
    arrowRight: {
        active: require('./images/arrow-right.png'),
        disable: require('./images/icons/arrow_right_disable.png'),
    },
    taskIcon: require('./images/goal-card-paper.png'),
    tickIcon: require('./images/tick.png'),
    googleIcon: require('./images/google.png'),
    facebookIcon: require('./images/facebook.png'),
    emailIcon: require('./images/email.png'),
    lockIcon: require('./images/lock.png'),
    calendarIcon: require('./images/calendar.png'),
    showPasswordIcon: require('./images/show-password.png'),
    hidePassword: require('./images/hide-password.png'),
    checkOn: require('./images/check-on.png'),
    checkOff: require('./images/check-off.png'),
    forgetPasswordIcon: require('./images/lupa-kata-sandi.png'),
    successChangedSomethingIcon: require('./images/berhasil-diubah.png'),
    listHasSaved: require('./images/daftar-tersimpan.png'),
    arrowDownIcon: require('./images/arrow-down.png'),
    voiceIcon: require('./images/voice.png'),
    stopIcon: require('./images/stop.png'),
    playIcon: require('./images/play.png'),
    pauseIcon: require('./images/pause.png'),
    deleteAudioIcon: require('./images/delete-audio.png'),
    recommendationCheckIcon: require('./images/rekomendasi-check.png'),
    recommendationPlusIcon: require('./images/rekomendasi-plus.png'),
    waitingGoalInvitation: require('./images/waiting-goal-invitation.png'),
    imageNoNotif: require('./images/tidak-ada-notif.png'),
    cameraIcon: require('./images/camera.png'),
    noReferralIcon: require('./images/no-referal.png'),
    recommendationLinkActive: require('./images/link-rekomendasi-green.png'),
    linkRecommendationIcon: require('./images/link-rekomendasi.png'),
    detailGoalTotalTaskIcon: require('./images/detail-goal-total-task.png'),
    detailGoalTotalViewCountIcon: require('./images/detail-goal-total-view.png'),
    detailGoalTotalCopyIcon: require('./images/detail-goal-total-copy.png'),
    shareIcon: require('./images/share.png'),
    recommendationTotalViewWhiteIcon: require('./images/recommendation-total-view-white.png'),
    recommendationTotalCopyWhiteIcon: require('./images/recommendation-total-copy-white.png'),
    navBottomHomeonIcon: require('./images/home-on.png'),
    navBottomHomeoffIcon: require('./images/home-off.png'),
    plusIcon: require('./images/plus.png'),
    searchGray: require('./images/search-gray.png'),
    recommendationTotalViewIcon: require('./images/recommendation-total-view.png'),
    recommendationTotalCopyIcon: require('./images/recommendation-total-copy.png'),
    logoutIcon: require('./images/logout.png'),
    tickSquareIcon: require('./images/tick-square.png'),
    arrowRightIcon: require('./images/arrow-right-green.png'),
    otherUserJobIcon: require('./images/other-user-job.png'),
    otherUserPinIcon: require('./images/other-user-pin.png'),
    otherUserProfileIcon: require('./images/other-user-profile.png'),
    menuGoalChoosenIcon: require('./images/menu-goals-pilih.png'),
    copyGoalIcon: require('./images/copy-goal.png'),
    predefinedGoalTotalTaskIcon: require('./images/predefined-goal-total-task.png'),
    predefinedGoalTotalViewIcon: require('./images/predefined-goal-total-view.png'),
    predefineGoalTotalCopyIcon: require('./images/predefined-goal-total-copy.png'),
    closeIconGray: require('./images/close-gray.png'),
    smallPinIcon: require('./images/small-pin.png'),
    smallHeartIcon: require('./images/small-heart.png'),
    smallProfileIcon: require('./images/small-profile.png'),
    pencilEditIcon: require('./images/pencil-edit.png'),
    tickOffIcon: require('./images/tick-off-task.png'),
    tickOnIcon: require('./images/tick-on-task.png'),
    tickOffTaskRed: require('./images/tick-off-task-red.png'),
    copyRecommendationGoalIcon: require('./images/copy-recommendation-goal.png'),
    searchIconColorGreen: require('./images/search-green.png'),
    pinTaskIcon: require('./images/pin-task.png'),
    arrowRightChevIcon: require('./images/arrow-right-chevron.png'),
    imageSuccessed: require('./images/berhasil-pin-goal.png'),
    imageSuccessedSave: require('./images/berhasil-disimpan.png'),
    plusGrayIcon: require('./images/plus-gray.png'),
    arrowDownGrayIcon: require('./images/arrow-down-gray.png'),
    intro: {
        introBottomBackground: require('./images/intro-bottom-background.png'),
        introButtonBackground: require('./images/intro-button-background.png'),
        introArrow: require('./images/intro-arrow.png'),
    },
    buttonDetailGoal: require('./images/buttonDetailGoal.png'),
    searchOn: require('./images/search-on.png'),
    searchOff: require('./images/search-off.png'),
    notificationOn: require('./images/notification-on.png'),
    notificationOff: require('./images/notification-off.png'),
    profileOn: require('./images/profile-on.png'),
    profileOff: require('./images/profile-off.png'),
    goalCardShare: require('./images/goal-card-share.png'),
    tickOnTaskRed: require('./images/tick-on-task-red.png'),
    repeat: require('./images/repeat.png'),
    calendarTask: require('./images/calendar-task.png'),
    calendarTaskRed: require('./images/calendar-task-red.png'),
    threeDots: require('./images/three-dots.png'),
    lampIdea: require('./images/lamp-idea.png'),
    repeatAlternate: require('./images/repeat-2.png'),
    addUser: require('./images/add-user.png'),
    plusGreen: require('./images/plus-green.png'),
    reloadIcon: require('./images/reload.png'),
    tickEditTask: require('./images/tick-edit-task.png'),
    tickCloseTask: require('./images/tick-close-task.png'),
    menuTaskDelete: require('./images/menu-task-delete.png'),
    menuTaskPin: require('./images/menu-task-pin.png'),
    menuTaskEdit: require('./images/menu-task-edit.png'),
    successSave: require('./images/simpan-perubahan.png'),
    goalBecomeTemplate: require('./images/menu-goal-jadikan-template.png'),
    addingTask: require('./images/menu-goal-tambah-task.png'),
    addUserGray: require('./images/add-user-gray.png'),
    repeatAlternateSecond: require('./images/repeat-3.png'),
    calendarCreateTask: require('./images/calendar-create-task.png'),
    plusSquare: require('./images/plus-square.png'),
    addingFriendinGoal: require('./images/menu-goal-tambah-teman.png'),
    splashScreenv2: require('./images/splash-screen-logo.png'),
    headerBackArrowImage: require('./images/header-back-arrow.png'),
    arrowleftGray: require('./images/arrow-left-gray.png'),
    arrowLeftGreen: require('./images/arrow-left-green.png'),
    rightIconDisableChevron: require("./images/icons/arrow_down_circle.png"),
    lockIconLine: require('./images/icons/majesticons_lock-line.png'),
    unlockIconLine: require('./images/icons/majesticons_unlock-open-line.png'),
    rightWhite: require('./images/icons/charm_arrow-right.png'),
    alternativeCopy: require('./images/icons/green_copy.png'),

    // brand new illustration
    emptyTask: require('./images/illustrations/empty.png'),
    offlineMode: require('./images/illustrations/offline_mode.png'),
    emptySearch: require('./images/illustrations/empty_search.png'),
    noInternetIcon: require('./images/illustrations/offline_mode.png'),
    imageYesNo: require('./images/illustrations/yakin_hapus.png'),
    adsSample: require('./images/sample/ads.png')

    // legacy illustration
    // offlineMode: require('./images/offline-mode.png'),
    // emptyTask: require('./images/belum-ada-task.png'),
    // noInternetIcon: require('./images/tidak-ada-internet.png'),
    // imageYesNo: require('./images/yes-no.png'),
}

export default images
